apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziralink-server.fullname" . }}
stringData:
  ZIRALINK_CONNECTIONSTRINGS_RABBITMQ: {{ .Values.environmentVariables.connectionStrings.rabbitmq }}
  ZIRALINK_REDIS_PASSWORD: {{ .Values.environmentVariables.redisPassword }}
  # ASPNETCORE_Kestrel__Certificates__Default__Password: {{ .Values.environmentVariables.certificatePassword }}
  